spring:
  application:
    name: ecs-config
  cloud:
    config:
    #仓库分支
      label: master
      server:
        git:
        #仓库地址
          uri: https://github.com/LeonLHZ/config.git
          #配置存放的目录
          search-paths: respo
          username: LeonLHZ
          password: Lhz@971009
  boot:
    admin:
      client:
        url: http://www.lhz520.cn:8081/api/admin
        instance:
         service-base-url: http://www.lhz520.cn:8081/api/config

  zipkin:
    base-url: http://116.62.156.171:8082
server:
  port: 8888


eureka:
  client:
  #注册服务到服务注册中心
    register-with-eureka: true
    service-url:
        defaultZone: http://116.62.156.171:8761/eureka/
  instance:
  #设置健康检查页面
    #health-check-url: http://${eureka.instance.ip-address}:${eureka.instance.non-secure-port}/health
    #配置状态页面为swagger-bootstrap-ui（封装swagger的开源项目，用户界面比较友好，推荐一个）接口页面，默认为项目的info端点页面
    #status-page-url: http://${eureka.instance.ip-address}:${eureka.instance.non-secure-port}/doc.html
    #设置实例ID名称
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${eureka.instance.non-secure-port}
    #设置使用IP
    prefer-ip-address: true
    #设置外网IP号
    ip-address: 94.191.119.192
    #设置外网端口号
    non-secure-port: 8888


management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  file: "/root/ecs/config-log.log"
  level:
    cn.lhz: debug
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%thread]){faint} %clr(%-40.40logger{39}){cyan} %L %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"

