spring:
  application:
    name: ecs-config
  cloud:
    config:
    #仓库分支
      label: master
      server:
        git:
        #仓库地址
          uri: https://github.com/LeonLHZ/config.git
          #配置存放的目录
          search-paths: respo
          username: LeonLHZ
          password: Lhz@971009
  boot:
    admin:
      client:
        url: http://94.191.119.192:8083
        instance:
              service-base-url: http://94.191.119.192:8888
  zipkin:
    base-url: http://94.191.119.192:8082
server:
  port: 8888


eureka:
  instance:
    prefer-ip-address: true
  #注册地址
  client:
    service-url:
      defaultZone: http://www.lhz520.cn:8761/eureka/

logging:
  file: /root/ecs/config-logs.log
  level:
    cn.lhz: debug
  pattern:
    file: %clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx

