spring:
  application:
    name: ecs-config
  cloud:
    config:
    #仓库分支
      label: master
      server:
        git:
        #仓库地址
          uri: https://github.com/LeonLHZ/config.git
          #配置存放的目录
          search-paths: respo
          username: LeonLHZ
          password: Lhz@971009
  boot:
    admin:
      client:
        url: http://www.lhz520.cn:8081/api/admin
        instance:
         service-base-url: http://www.lhz520.cn:8081/api/config

  zipkin:
    base-url: http://116.62.156.171:8082
server:
  port: 8888


eureka:
  instance:
    prefer-ip-address: true
  #注册地址
  client:
    service-url:
      defaultZone: http://www.lhz520.cn:8081/api/eureka/


management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  file: "/root/ecs/config-log.log"
  level:
    cn.lhz: debug
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%thread]){faint} %clr(%-40.40logger{39}){cyan} %L %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"

