spring:
  application:
    name: esc-config
  cloud:
    config:
    #仓库分支
      label: master
      server:
        git:
        #仓库地址
          uri: https://github.com/LeonLHZ/config.git
          #配置存放的目录
          search-paths: respo
          username: LeonLHZ
          password: Lhz@971009
server:
  port: 8888


eureka:
  instance:
    prefer-ip-address: true
  #注册地址
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
